# Generated by Django 3.1.6 on 2021-02-12 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
            ],
        ),
    ]
