# Generated by Django 3.1.6 on 2021-02-13 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Map', '0002_places_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='places',
            name='icon_type',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
