# Generated by Django 3.1.6 on 2021-02-13 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Map', '0003_places_icon_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Places',
            new_name='Place',
        ),
    ]
