# Generated by Django 3.1.6 on 2021-02-13 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Map', '0004_auto_20210213_0735'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='category',
            field=models.CharField(blank=True, choices=[('Food', 'Food'), ('Shelter', 'Shelter'), ('Voice', 'Voice'), ('COVID-19', 'COVID-19'), ('Litter Picking', 'Litter Picking')], max_length=100, null=True),
        ),
    ]
