# Generated by Django 3.1.6 on 2021-02-13 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Map', '0005_place_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='icon_type',
        ),
    ]
